### ISSUE TITLE
subscribeSpyTo<T> returns SubscriberSpy<unknown> instead of SubscriberSpy<T>

### ISSUE THREAD

**Issue by batbrain9392** [hirezio/observer-spy#43] opened 2021-12-21 09:17 UTC
**Describe the bug**
`subscribeSpyTo<T>` returns `SubscriberSpy<unknown>` instead of `SubscriberSpy<T>`

**To Reproduce**
1. Create a new angular project
2. Install @hirez_io/observer-spy
3. Use subscribeSpyTo to test a string observable, for example - `of('str')`
4. See that it returns `SubscriberSpy<unknown>` instead of `SubscriberSpy<string>`

**Expected behavior**
It should return `SubscriberSpy<string>` instead of `SubscriberSpy<unknown>`

**Screenshots**
Bug -
![image](https://user-images.githubusercontent.com/16289648/146903949-a8df2bf3-987f-4549-9c99-27c19387848d.png)
Source code for subscribeSpyTo -
![image](https://user-images.githubusercontent.com/16289648/146903982-929e4729-edc7-4eea-941f-5c162e614587.png)

**Desktop (please complete the following information):**
Angular CLI: 13.1.2
Node: 14.18.2
Package Manager: npm 6.14.15
OS: linux x64

Angular: 13.1.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1301.2
@angular-devkit/build-angular   13.1.2
@angular-devkit/core            13.1.2
@angular-devkit/schematics      13.1.2
@angular/cli                    13.1.2
@schematics/angular             13.1.2
rxjs                            7.4.0
typescript                      4.5.4

**Comment by shairez** [comment] 2021-12-21 10:35
Thanks for the report @batbrain9392 !

Can you show how `title$` is configured?

**Comment by batbrain9392** [comment] 2021-12-21 10:43
title$ = of('str')

**Comment by shairez** [comment] 2021-12-21 10:49
That's weird.. 
When I try to reproduce I get this - 

![image](https://user-images.githubusercontent.com/1430726/146917458-0a74de2f-09f4-4c68-b3ed-5ab43a2fe2e0.png)

![image](https://user-images.githubusercontent.com/1430726/146917549-2eaa74a8-3042-4630-bc71-ef5d7214b69f.png)

which version of Observer-spy are you using? the latest?

Trying to think of reasons - maybe it's because it's on a different file? 🤔

**Comment by batbrain9392** [comment] 2021-12-21 12:50
I'm using the latest version (installed using `@latest`).

**Comment by shairez** [comment] 2022-01-02 12:16
OK I managed to fix it (somehow) in version 2.1.2

For some reason, only the `.d.ts` files generated by the CI build got `unknown` as generics (while locally it was building with the correct `<T>` generic)

So I re-ran the build and it built it correctly this time 

No clue to why it got messed up, but my guess is a TypeScript version voodoo 🤷‍♀️😅

Anyway, please test it and see if it works (closing for now)

**Closed as completed by shairez** 2022-01-02 12:16 UTC

**Comment by batbrain9392** [comment] 2022-01-11 09:07
Thanks a ton, Shai! It works now.
